# import libraries
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

# get env
load_dotenv()

# load variables
# get from env
postgres = os.getenv("POSTGRES")
mysql = os.getenv("MYSQL")
mssql = os.getenv("MSSQL")

# building engines for relational databases
# postgres, mysql and mssql
postgres_engine = create_engine(postgres)
mysql_engine = create_engine(mysql)
mssql_engine = create_engine(mssql)

"""
# postgres
create table public.beer
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    id bigint,
	uid text,
	brand text,
	name text,
	style text,
	hop text,
	yeast text,
	malts text,
	ibu text,
	alcohol text,
	blg text,
	user_id bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

create table public.coffee
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    id bigint,
	uid text,
	blend_name text,
	origin text,
	variety text,
	notes text,
	intensifier text,
	user_id bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

create table public.food
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    id bigint,
	uid text,
	dish text,
	description text,
	ingredient text,
	measurement text,
	user_id bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

create table public.dessert
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    id bigint,
	uid text,
	variety text,
	topping text,
	flavor text,
	user_id bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

create table public.albums
(
	incr int GENERATED BY DEFAULT AS IDENTITY,
    artist_id bigint,
	album_title text,
	genre text,
	year_of_pub bigint,
	num_of_tracks bigint,
	num_of_sales bigint,
	rolling_stone_critic bigint,
	mtv_critic bigint,
	music_maniac_critic bigint,
	dt_current_timestamp timestamp,
	PRIMARY KEY (incr)
);

# mysql
create table owshq.commerce
(
	incr int AUTO_INCREMENT,
    id bigint null,
	uid text null,
	color text null,
	department text null,
	material text null,
	product_name text null,
	price double null,
	price_string text null,
	promo_code text null,
	user_id bigint null,
	dt_current_timestamp datetime null,
    PRIMARY KEY (incr)
);

create table owshq.computer
(
	incr int AUTO_INCREMENT,
    id bigint null,
	uid text null,
	platform text null,
	type text null,
	os text null,
	stack text null,
	user_id bigint null,
	dt_current_timestamp datetime null,
	PRIMARY KEY (incr)
);

create table owshq.device
(
	incr int AUTO_INCREMENT,
    id bigint null,
	uid text null,
	build_number bigint null,
	manufacturer text null,
	model text null,
	platform text null,
	serial_number text null,
	version bigint null,
	user_id bigint null,
	dt_current_timestamp datetime null,
	PRIMARY KEY (incr)
);

# mssql
create table dbo.bank
(
    incr int IDENTITY(1,1) PRIMARY KEY,
	id bigint,
	uid varchar(max),
	account_number varchar(max),
	iban varchar(max),
	bank_name varchar(max),
	routing_number varchar(max),
	swift_bic varchar(max),
	user_id bigint,
	dt_current_timestamp datetime,
	dt_creation datetime2 default CURRENT_TIMESTAMP
)
go

create table dbo.credit_card
(
    incr int IDENTITY(1,1) PRIMARY KEY,
	id bigint,
	uid varchar(max),
	credit_card_number varchar(max),
	credit_card_expiry_date varchar(max),
	credit_card_type varchar(max),
	user_id bigint,
	dt_current_timestamp datetime,
	dt_creation datetime2 default CURRENT_TIMESTAMP
)
go

create table dbo.subscription
(
    incr int IDENTITY(1,1) PRIMARY KEY,
	id bigint,
	uid varchar(max),
	[plan] varchar(max),
	status varchar(max),
	payment_method varchar(max),
	subscription_term varchar(max),
	payment_term varchar(max),
	user_id bigint,
	dt_current_timestamp datetime,
	dt_creation datetime2 default CURRENT_TIMESTAMP
)
go

create table dbo.company
(
    incr int IDENTITY(1,1) PRIMARY KEY,
	id bigint,
	uid varchar(max),
	business_name varchar(max),
	suffix varchar(max),
	industry varchar(max),
	catch_phrase varchar(max),
	buzzword varchar(max),
	bs_company_statement varchar(max),
	employee_identification_number varchar(max),
	duns_number varchar(max),
	logo varchar(max),
	type varchar(max),
	phone_number varchar(max),
	full_address varchar(max),
	latitude float,
	longitude float,
	user_id bigint,
	dt_current_timestamp datetime,
	dt_creation datetime2 default CURRENT_TIMESTAMP
)
go
"""