apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # app name
  name: cruise-control
  # deployed yaml
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 'https://bitbucket.org/owshq/big-data-on-k8s.git'
    path: repository/yamls/ingestion/cruise-control/
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingestion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
